blueprints/dashboard.py
import datetime

from flask import Blueprint, render_template, session
from database import *
from login import require_login

routes_dashboard = Blueprint("dashboard", __name__, template_folder="../templates/dashboard")


@routes_dashboard.route("/dashboard")
@require_login
def overview():
    user = db_users.find_one({"email": session.get("email")})

    list_items = list(db_items.find({"user": user["_id"]}))
    daily_stats = list(db_items.aggregate([{
        "$match": {
            "created_on": {
                "$gte": datetime.datetime.today() - datetime.timedelta(days=1)
            },
            "user": user["_id"]
        }
    }, {"$group": {
        "_id": None,
        "amount": {"$sum": "$calories"}
    }}, {"$limit": 1}]))

    goals = db_goals.find_one({"user": user["_id"]})
    daily_goal = goals["daily_goal"] if goals else 0
    daily_calories = daily_stats[0]["amount"] if len(daily_stats) != 0 else 0

    return render_template("overview.html", items=list_items, daily_calories=daily_calories, daily_goal=daily_goal)


@routes_dashboard.route("/dashboard/goals", methods=["GET"])
@require_login
def goals():
    user = db_users.find_one({"email": session.get("email")})

    goals = db_goals.find_one({"user": user["_id"]})
    health_goals = goals["health_goals"] if goals else []
    daily_goal = goals["daily_goal"] if goals else 0
    return render_template("goals.html", health_goals=enumerate(health_goals), daily_goal=daily_goal)

blueprints/dashboard/views.py
import datetime

from flask import Blueprint, render_template, session
from database import *
from login import require_login

view = Blueprint("dashboard", __name__, template_folder="templates")


@view.route("/dashboard")
@require_login
def overview():
    user = db_users.find_one({"email": session.get("email")})

    list_items = list(db_items.find({"user": user["_id"]}))
    daily_stats = list(db_items.aggregate([{
        "$match": {
            "created_on": {
                "$gte": datetime.datetime.today() - datetime.timedelta(days=1)
            },
            "user": user["_id"]
        }
    }, {"$group": {
        "_id": None,
        "amount": {"$sum": "$calories"}
    }}, {"$limit": 1}]))

    daily_goal = db_goals.find_one({"user": user["_id"], "category": "daily"}, {"amount": 1})
    daily_goal = daily_goal["amount"] if daily_goal else 0
    daily_calories = daily_stats[0]["amount"] if len(daily_stats) != 0 else 0

    return render_template("overview.html", items=list_items, daily_calories=daily_calories, daily_goal=daily_goal)


@view.route("/dashboard/goals", methods=["GET"])
@require_login
def goals():
    user = db_users.find_one({"email": session.get("email")})

    # Only one goal right now
    daily_goal = db_goals.find_one({"user": user["_id"]})
    return render_template("goals.html", daily_goal=daily_goal)

blueprints/main.py
from flask import Blueprint, render_template, redirect, url_for, flash, session, request
from database import *
from werkzeug.security import check_password_hash

routes_main = Blueprint("main", __name__)


@routes_main.route("/")
def index():
    return render_template("index.html")


@routes_main.route("/login")
def login():
    if session.get("email"):
        return redirect(url_for("dashboard.overview"))
    return render_template("login.html")


@routes_main.route("/login", methods=["POST"])
def login_user():
    if session.get("email"):
        return redirect(url_for("dashboard.overview"))

    user = db_users.find_one({"email": request.form.get("email")})
    password = request.form.get("password")

    if not user or not check_password_hash(user["password"], password):
        flash("Incorrect login!", "danger")
        return redirect(url_for("main.login"))

    session["email"] = user.get("email", "danger")
    return redirect(url_for("dashboard.overview"))


@routes_main.route("/register")
def register():
    return render_template("register.html")


@routes_main.route("/logout")
def logout_user():
    session.pop("email", None)
    flash("You are now logged out", "success")
    return redirect(url_for("main.login"))

templates/partials/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Calorie Tally</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='styles/styles.css') }}">

    {% block head %}
    {% endblock %}
</head>
<body>
{% include "partials/nav.html" %}

<main class="fill">
    {% block content %}
    {% endblock %}
</main>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>

templates/partials/dashboard.html
{% extends "partials/base.html" %}
{% set active_page = "dashboard" %}

{% block content %}
<div class="container-fluid p-0 h-100">
    <div class="row h-100 w-100 m-0 p-0">
        <div class="col-2 h-100 p-0">
            <div class="h-100 d-flex align-content-center flex-column p-2">
                <ul class="nav nav-pills flex-column mb-auto">
                    <li class="nav-item dashboard-item">
                        <a href="{{ url_for('dashboard.overview')}}"
                           class="nav-link {{ 'active' if dashboard_page == 'overview' else 'text-dark'}}">
                            <i class="text-center bi bi-house d-block d-md-none"></i>
                            <span class="d-md-block d-none">Overview</span>
                        </a>
                    </li>
                    <li class="nav-item dashboard-item">
                        <a href="{{ url_for('dashboard.goals') }}"
                           class="nav-link {{ 'active' if dashboard_page == 'goals' else 'text-dark'}}">
                            <i class="text-center bi bi-plus-circle d-block d-md-none"></i>
                            <span class="d-md-block d-none">Goals</span></a>
                    </li>
                </ul>
                <hr>
                <a href="{{ url_for('main.logout_user') }}" class="text-center text-dark text-decoration-none">
                    <i class="d-inline-block bi bi-box-arrow-right"></i>
                    <span class="d-md-inline-block d-none">Logout</span>
                </a>
            </div>
        </div>
        <div class="col-10 bg-light d-flex align d-flex flex-column p-0">
            {% block dashboard_items %}

            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}

templates/partials/nav.html
<nav class="navbar navbar-expand-md navbar-light">
    <div class="container-fluid px-4">
        <p class="navbar-brand p-0 m-0">Calorie Tally</p>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbar-links">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar-links">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link {{ 'active' if active_page == 'index'}}" href="{{ url_for('main.index') }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ 'active' if active_page == 'dashboard'}}" href="{{ url_for('dashboard.overview') }}">Dashboard</a>
                </li>
            </ul>
        </div>
    </div>
</nav>