blueprints/main.py
from flask import Blueprint, render_template, redirect, url_for, flash, session, request
from database import *
from werkzeug.security import check_password_hash

routes_main = Blueprint("main", __name__)


@routes_main.route("/")
def index():
    return render_template("index.html")


@routes_main.route("/login")
def login():
    if session.get("email"):
        return redirect(url_for("dashboard.overview"))
    return render_template("login.html")


@routes_main.route("/login", methods=["POST"])
def login_user():
    if session.get("email"):
        return redirect(url_for("dashboard.overview"))

    user = db_users.find_one({"email": request.form.get("email")})
    password = request.form.get("password")

    if not user or not check_password_hash(user["password"], password):
        flash("Incorrect login!", "danger")
        return redirect(url_for("main.login"))

    session["email"] = user.get("email", "danger")
    return redirect(url_for("dashboard.overview"))


@routes_main.route("/register")
def register():
    return render_template("register.html")


@routes_main.route("/logout")
def logout_user():
    session.pop("email", None)
    flash("You are now logged out", "success")
    return redirect(url_for("main.login"))

templates/index.html
{% extends "partials/base.html" %}
{% set active_page = "index" %}

{% block head %}
<style>
    .navbar {
        position: fixed;
        top: 0;
        right: 0;
        left: 0;
    }

    .navbar-toggler {
        border: none;
    }

</style>
{% endblock %}

{% block content %}
<section class="vh-100 hero">
    <div class="container-fluid h-100">
        <header class="h-100 d-flex align-items-center justify-content-center">
            <div class="text-center">
                <h1 class="display-1 mb-0">Calorie Tally</h1>
                <p class="lead">Count your daily calories!</p>
                <a href="/dashboard" class="btn btn-outline-dark btn-md mt-2 px-3">Get Started</a>
            </div>
        </header>
    </div>
</section>
{% endblock %}

templates/login.html
{% extends "partials/base.html" %}
{% set active_page = "dashboard" %}

{% block content %}
<div class="container-fluid bg-light h-100 d-flex justify-content-center align-items-center">
    <div class="card w-50 flex-fill flex-sm-grow-0">
        <div class="card-body">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% for category, message in messages %}

            <div class="alert alert-{{ category }}" role="alert">
                {{ message }}
            </div>

            {% endfor %}
            {% endwith %}

            <h1 class="card-title">Login</h1>
            <form action="/login" method="POST">
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" id="email" name="email" class="form-control" placeholder="Email" value="john.doe@example.com" required>
                </div>
                <div class="form-group mt-2">
                    <label for="password">Password</label>
                    <input type="password" id="password" name="password" class="form-control" placeholder="Password" value="Password" required>
                </div>
                <div class="text-center">
                    <button class="btn btn-md btn-primary mt-2 py-1 w-100" type="submit">Sign in</button>
                    <hr>
                    <small>Or <a href="{{ url_for('main.register') }}">Sign Up</a></small>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/register.html
{% extends "partials/base.html" %}
{% set active_page = "dashboard" %}

{% block content %}
<div class="container-fluid bg-light h-100 d-flex justify-content-center align-items-center">
    <div class="card w-50 flex-fill flex-sm-grow-0">
        <div class="card-body">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% for category, message in messages %}

            <div class="alert alert-{{ category }}" role="alert">
                {{ message }}
            </div>

            {% endfor %}
            {% endwith %}

            <h1 class="card-title">Register</h1>
            <form action="/users/" method="POST">
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" id="name" name="name" class="form-control" placeholder="Name"
                           required>
                </div>
                <div class="form-group mt-2">
                    <label for="email">Email</label>
                    <input type="email" id="email" name="email" class="form-control" placeholder="Your email"
                           required>
                </div>
                <div class="form-group mt-2">
                    <label for="password">Password</label>
                    <input type="password" id="password" name="password" class="form-control"
                           placeholder="Your password" required>
                </div>
                <div class="text-center">
                    <button class="btn btn-md btn-primary mt-2 py-1 w-100" type="submit">Sign up</button>
                    <hr>
                    <small>Or <a href="{{ url_for('main.login') }}">Sign In</a></small>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}