blueprints/dashboard.py
import datetime

from flask import Blueprint, render_template, session
from database import *
from login import require_login

routes_dashboard = Blueprint("dashboard", __name__, template_folder="../templates/dashboard")


@routes_dashboard.route("/dashboard")
@require_login
def overview():
    user = db_users.find_one({"email": session.get("email")})

    list_items = list(db_items.find({"user": user["_id"]}))
    daily_stats = list(db_items.aggregate([{
        "$match": {
            "created_on": {
                "$gte": datetime.datetime.today() - datetime.timedelta(days=1)
            },
            "user": user["_id"]
        }
    }, {"$group": {
        "_id": None,
        "amount": {"$sum": "$calories"}
    }}, {"$limit": 1}]))

    goals = db_goals.find_one({"user": user["_id"]})
    daily_goal = goals["daily_goal"] if goals else 0
    daily_calories = daily_stats[0]["amount"] if len(daily_stats) != 0 else 0

    return render_template("overview.html", items=list_items, daily_calories=daily_calories, daily_goal=daily_goal)


@routes_dashboard.route("/dashboard/goals", methods=["GET"])
@require_login
def goals():
    user = db_users.find_one({"email": session.get("email")})

    goals = db_goals.find_one({"user": user["_id"]})
    health_goals = goals["health_goals"] if goals else []
    daily_goal = goals["daily_goal"] if goals else 0
    return render_template("goals.html", health_goals=enumerate(health_goals), daily_goal=daily_goal)

blueprints/dashboard/views.py
import datetime

from flask import Blueprint, render_template, session
from database import *
from login import require_login

view = Blueprint("dashboard", __name__, template_folder="templates")


@view.route("/dashboard")
@require_login
def overview():
    user = db_users.find_one({"email": session.get("email")})

    list_items = list(db_items.find({"user": user["_id"]}))
    daily_stats = list(db_items.aggregate([{
        "$match": {
            "created_on": {
                "$gte": datetime.datetime.today() - datetime.timedelta(days=1)
            },
            "user": user["_id"]
        }
    }, {"$group": {
        "_id": None,
        "amount": {"$sum": "$calories"}
    }}, {"$limit": 1}]))

    daily_goal = db_goals.find_one({"user": user["_id"], "category": "daily"}, {"amount": 1})
    daily_goal = daily_goal["amount"] if daily_goal else 0
    daily_calories = daily_stats[0]["amount"] if len(daily_stats) != 0 else 0

    return render_template("overview.html", items=list_items, daily_calories=daily_calories, daily_goal=daily_goal)


@view.route("/dashboard/goals", methods=["GET"])
@require_login
def goals():
    user = db_users.find_one({"email": session.get("email")})

    # Only one goal right now
    daily_goal = db_goals.find_one({"user": user["_id"]})
    return render_template("goals.html", daily_goal=daily_goal)

blueprints/goals.py
from flask import Blueprint, session, redirect, url_for, flash, request, render_template
from database import *
from login import require_login
from datetime import datetime
from bson.objectid import ObjectId

routes_goals = Blueprint("goals", __name__, url_prefix="/goals")


@routes_goals.route("/", methods=["POST"])
@require_login
def create():
    user = db_users.find_one({"email": session.get("email")})
    existing_goals = db_goals.find_one({"user": user["_id"]})

    if "update_daily" in request.form:
        amount = request.form.get("amount")
        if not amount:
            flash("There were one or more missing fields!", "danger")
            return redirect(url_for("dashboard.goals"))

        try:
            amount = int(amount)
        except ValueError:
            flash("Invalid input: amount!", "danger")
            return redirect(url_for("dashboard.goals"))

        db_goals.update_one({
            "user": user["_id"],
        }, {
            "$set": {
                "daily_goal": amount,
                "health_goals": existing_goals["health_goals"] if existing_goals else []
            }
        }, upsert=True)
        flash("Daily goal updated!", "success")
    elif "add_goal" in request.form:
        goal_text = request.form.get("goal_text")

        if not goal_text:
            flash("There were one or more missing fields!", "danger")
            return redirect(url_for("goals.new"))

        db_goals.update_one({
            "user": user["_id"],
        }, {
            "$set": {
                "daily_goal": existing_goals["daily_goal"] if existing_goals else 0
            },
            "$push": {
                "health_goals": {
                    "_id": ObjectId(),
                    "goal": goal_text,
                    "created_on": datetime.today()
                }
            }
        }, upsert=True)
        flash("Health goal added!", "success")
    return redirect(url_for("dashboard.goals"))


@routes_goals.route("/new", methods=["GET"])
@require_login
def new():
    return render_template("goal_new.html")


@routes_goals.route("/<string:item_id>", methods=["DELETE"])
@require_login
def destroy(item_id):
    user = db_users.find_one({"email": session.get("email")})

    db_goals.update_one({
        "user": user["_id"],
    }, {
        "$pull": {
            "health_goals": {
                "_id": ObjectId(item_id)
            }
        }
    })
    return "", 204

blueprints/goals/views.py
from flask import Blueprint, session, redirect, url_for, flash, request
from database import *
from login import require_login

view = Blueprint("goals", __name__, url_prefix="/goals")


@view.route("/", methods=["POST"])
@require_login
def create():
    user = db_users.find_one({"email": session.get("email")})
    amount = request.form.get("amount")
    category = request.form.get("category")

    if not amount or not category or category not in ["daily"]:
        flash("There were one or more missing fields!", "danger")
        return redirect(url_for("dashboard.goals"))

    try:
        amount = int(amount)
    except ValueError:
        flash("Invalid input: amount!", "danger")
        return redirect(url_for("dashboard.goals"))

    db_goals.update_one({
        "user": user["_id"],
        "category": category
    }, {
        "$set": {"amount": amount}
    }, upsert=True)
    flash("Goal updated!", "success")
    return redirect(url_for("dashboard.goals"))

blueprints/items.py
from flask import Blueprint, session, redirect, url_for, request, flash
from database import *
from bson.objectid import ObjectId

from datetime import datetime
from login import require_login

routes_items = Blueprint("items", __name__, url_prefix="/items")


@routes_items.route("/", methods=["POST"])
@require_login
def create():
    user = db_users.find_one({"email": session.get("email")})
    item_name = request.form.get("item_name")
    item_calories = request.form.get("item_calories")
    if not item_name or not item_calories:
        flash("There were one or more missing fields!", "danger")
        return redirect(url_for("dashboard.overview"))

    try:
        item_calories = int(item_calories)
    except ValueError:
        flash("Invalid input: calories!", "danger")
        return redirect(url_for("dashboard.overview"))

    db_items.insert_one({
        "user": user["_id"],
        "name": item_name,
        "calories": item_calories,
        "created_on": datetime.today()
    })
    return redirect(url_for("dashboard.overview"))


@routes_items.route("/<string:item_id>", methods=["DELETE"])
@require_login
def destroy(item_id):
    user = db_users.find_one({"email": session.get("email")})

    db_items.delete_one({"_id": ObjectId(item_id), "user": user["_id"]})
    return "", 204

templates/dashboard/goal_new.html
{% extends "partials/dashboard.html" %}
{% set active_page = "dashboard" %}
{% set dashboard_page = "goals" %}

{% block head %}

{% endblock %}

{% block dashboard_items %}
<div class="mx-4 mb-0 mt-2">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% for category, message in messages %}

    <div class="alert alert-{{ category }}" role="alert">
        {{ message }}
    </div>

    {% endfor %}
    {% endwith %}
</div>
<div class="mx-4 p-2 shadow-sm border bg-white">
    <h1 class="h3">Add a Goal</h1>
    <form action="{{url_for('goals.create')}}" method="POST">
        <div class="form-group">
            <label for="goal">Goal</label>
            <input type="text" class="form-control" id="goal" placeholder="Goal" name="goal_text" required>
        </div>
        <button type="submit" name="add_goal" class="mt-2 btn btn-sm btn-dark">Submit</button>
    </form>
</div>
{% endblock %}

templates/dashboard/goals.html
{% extends "partials/dashboard.html" %}
{% set active_page = "dashboard" %}
{% set dashboard_page = "goals" %}

{% block head %}

{% endblock %}

{% block dashboard_items %}
<div class="mx-4 mb-0 mt-2">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% for category, message in messages %}

    <div class="alert alert-{{ category }}" role="alert">
        {{ message }}
    </div>

    {% endfor %}
    {% endwith %}
</div>
<div class="mx-4 mt-2 bg-white shadow-sm p-2">
    <h1 class="h2">Goals</h1>
    <form action="{{ url_for('goals.create') }}" method="POST">
        <label for="amount">Daily</label>
        <div class="input-group">
            <input type="number" name="amount" class="form-control" id="amount" placeholder="Amount"
                   value="{{daily_goal}}" min=0>
            <button class="btn btn-sm btn-success" name="update_daily" type="submit">Update</button>
        </div>
    </form>
    <h2 class="mt-4 h4">Health Goals</h2>
    <a href="{{ url_for('goals.new') }}" class="text-dark">Add Goal</a>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Goal</th>
            <th scope="col">Options</th>
        </tr>
        </thead>
        <tbody>
        {% for (i, goal) in health_goals %}
        <tr>
            <th>{{ i + 1}}</th>
            <td>{{ goal.goal }}</td>
            <td>
                <button type="button" class="btn-goal-delete bi bi-x-lg mx-2 text-danger"
                        data-id="{{goal._id}}"
                        style="font-size: 1em; border: none; background-color: transparent;"></button>
            </td>
        </tr>
        {% else %}
        <tr>
            <td colspan="3">No goals</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<script>
    const deleteButtons = document.querySelectorAll(".btn-goal-delete");
    deleteButtons.forEach(button => button.addEventListener("click", handleClick));

    function handleClick(e) {
        const target = e.currentTarget;
        const item_id = target.dataset.id;
        if (!item_id) return;

        fetch(`/goals/${item_id}`, {
            method: "DELETE"
        }).then(() => {
            window.location.reload();
        });
    }
</script>
{% endblock %}

templates/dashboard/overview.html
{% extends "partials/dashboard.html" %}
{% set active_page = "dashboard" %}
{% set dashboard_page = "overview" %}

{% block head %}
<style>
    .btn-custom-edit {
        visibility: hidden;
        position: absolute;

        border: none;
        color: black;
        background: none;

        top: 15px;
        right: 10px;
    }

    .card-body:hover .btn-custom-edit {
        visibility: visible;
    }
</style>
{% endblock %}

{% block dashboard_items %}
<div class="mx-4 mt-4">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% for category, message in messages %}

    <div class="alert alert-{{ category }}" role="alert">
        {{ message }}
    </div>

    {% endfor %}
    {% endwith %}
</div>
<div class="d-flex flex-row mx-4 flex-wrap">
    <div class="card shadow-sm flex-fill flex-md-grow-0">
        <div class="card-body">
            <i class="align-middle d-md-inline-block d-none bi bi-speedometer me-3" style="font-size: 2em"></i>
            <div class="align-middle d-inline-block">
                <h2 class="card-title">Today</h2>
                <p class="card-subtitle text-muted">{{daily_calories or 0}} cal</p>
            </div>
        </div>
    </div>
    <div class="card ms-md-4 shadow-sm flex-fill flex-md-grow-0">
        <div class="card-body">
            <i class="align-middle d-md-inline-block d-none bi bi-trophy me-3" style="font-size: 2em"></i>
            <div class="align-middle d-inline-block">
                <h2 class="card-title">Daily Goal</h2>
                <p class="card-subtitle text-muted">{{daily_calories}}/{{daily_goal}} cal
                    ({{((daily_calories / daily_goal * 100) | round(2)) if daily_calories and
                    daily_goal else 0}}%)</p>
            </div>
        </div>
    </div>
</div>
<div class="m-4 shadow-sm">
    <form action="{{ url_for('items.create') }}" method="POST">
        <div class="input-group">
            <input type="text" name="item_name" class="form-control d-block" placeholder="Name"
                   required>
            <input type="number" name="item_calories" class="form-control" placeholder="Calories" min="0"
                   required>

            <button class="btn btn-success" type="submit">Add</button>
        </div>
    </form>
</div>
<div class="row border bg-white mx-4 shadow-sm">
    <div class="col-12 m-0 border-bottom p-2">
        <h2 class="m-0 h4">Entries</h2>
    </div>
    {% for item in items %}
    <div class="col-12 col-sm-4">
        <div class="card my-4">
            <div class="card-body">
                <h3 class="card-title" style="font-size: 20px">{{item.name}}</h3>
                <p class="card-subtitle">{{item.calories}} cal</p>
                <small class="text-muted"><b>Logged on</b> {{ item.created_on.strftime("%m-%d-%Y")
                    }}</small>
                <button class="btn-custom-edit" data-id="{{item._id}}">
                    <i class="bi bi-trash"></i></button>
            </div>
        </div>
    </div>

    {% else %}
    <div class="col-12 py-3">
        <p class="text-muted my-auto">No Items yet</p>
    </div>
    {% endfor %}
</div>

<script>
    const deleteButtons = document.querySelectorAll(".btn-custom-edit");
    deleteButtons.forEach(button => button.addEventListener("click", handleClick));

    function handleClick(e) {
        const target = e.currentTarget;
        const item_id = target.dataset.id;
        if (!item_id) return;

        fetch(`/items/${item_id}`, {
            method: "DELETE"
        }).then(() => {
            window.location.reload();
        });
    }
</script>
{% endblock %}